apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-cop-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tap-cop-test
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      system: tutorials
      owner: cop-tap
      description: "A set of API endpoints."
  source:
    git:
      url: https://github.com/bkieling/tap-cop-test
      ref:
        branch: main
